name: react-app-express-js-ci-cd

on:
  push:
    branches:
      - main

  workflow_dispatch:

env:
  NODE-VERSION: 20
  AWS_REGION: ap-northeast-1

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.3.0
        with:
          node-version: ${{ env.NODE-VERSION }}

      - name: Install dependencies
        working-directory: ./express-backend
        run: npm install

      - name: Run unit tests
        working-directory: ./express-backend
        run: npm test

  format_code:
    runs-on: ubuntu-latest

    needs: unit-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.3.0
        with:
          node-version: ${{ env.NODE-VERSION }}

      - name: Install dependencies
        working-directory: ./express-backend
        run: npm install

      - name: Format code
        working-directory: ./express-backend
        run: npx prettier --write .

      - name: Push code
        working-directory: ./express-backend
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          if [[ $(git status --porcelain) ]]; then
            if ! git add .; then
              echo "Error: Failed to stage files"
              exit 1
            fi

            if ! git commit -m "Updated from ref: ${{ github.sha }}"; then
              echo "Error: Failed to commit files"
              exit 1
            fi

            if ! git push 2>&1 | tee push.log; then
              if grep -q "403" push.log; then
                echo "Error: Permission denied (HTTP 403). Exiting."
                exit 1
              fi

              if ! git pull --rebase && git push; then
                echo "Error: failed to push the code after rebase."
                exit 1
              fi
            fi
          else
            echo "Nothing to commit."
          fi

  deploy-app:
    runs-on: ubuntu-latest

    needs: format_code

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform
        run: |
          terraform fmt
          terraform validate
          terraform plan -var "run_number=${{ github.run_number }}"

      - name: Run Terraform
        working-directory: ./terraform
        run: |
          terraform apply -auto-approve -var "run_number=${{ github.run_number }}"

  destroy:
    runs-on: ubuntu-latest
    needs: deploy-app
    environment: destroy-infrastructure # Ties this job to the environment with approval
    if: github.event_name == 'workflow_dispatch' # Only runs on manual trigger
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Plan
        working-directory: ./terraform
        run: |
          terraform fmt
          terraform validate
          terraform plan -var "run_number=${{ github.run_number }}"

      - name: Terraform Destroy
        working-directory: ./terraform
        run: |
          terraform destroy -auto-approve -var "run_number=${{ github.run_number }}"
        
