name: test terraform cloud backend

on:
  pull_request:
    branches:
      - main

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    env:
      TF_TOKEN_app_terraform_io: "${{ secrets.TF_API_TOKEN }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform
        run: |
          terraform fmt
          terraform validate
          terraform plan

      - name: Deploy backend app
        working-directory: ./terraform
        run: terraform apply -auto-approve